# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: github.com/openconfig/gnoi/bootconfig/bootconfig.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'github.com/openconfig/gnoi/bootconfig/bootconfig.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from github.com.openconfig.bootz.proto import bootz_pb2 as github_dot_com_dot_openconfig_dot_bootz_dot_proto_dot_bootz__pb2
from github.com.openconfig.gnoi.types import types_pb2 as github_dot_com_dot_openconfig_dot_gnoi_dot_types_dot_types__pb2
from github.com.openconfig.gnsi.authz import authz_pb2 as github_dot_com_dot_openconfig_dot_gnsi_dot_authz_dot_authz__pb2
from github.com.openconfig.gnsi.certz import certz_pb2 as github_dot_com_dot_openconfig_dot_gnsi_dot_certz_dot_certz__pb2
from github.com.openconfig.gnsi.pathz import pathz_pb2 as github_dot_com_dot_openconfig_dot_gnsi_dot_pathz_dot_pathz__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6github.com/openconfig/gnoi/bootconfig/bootconfig.proto\x12\x0fgnoi.bootconfig\x1a-github.com/openconfig/bootz/proto/bootz.proto\x1a,github.com/openconfig/gnoi/types/types.proto\x1a,github.com/openconfig/gnsi/authz/authz.proto\x1a,github.com/openconfig/gnsi/certz/certz.proto\x1a,github.com/openconfig/gnsi/pathz/pathz.proto\"\x16\n\x14GetBootConfigRequest\"?\n\x15GetBootConfigResponse\x12&\n\x0b\x62oot_config\x18\x01 \x01(\x0b\x32\x11.bootz.BootConfig\"\x9e\x02\n\x14SetBootConfigRequest\x12&\n\x0b\x62oot_config\x18\x01 \x01(\x0b\x32\x11.bootz.BootConfig\x12\'\n\x0b\x63redentials\x18\x02 \x01(\x0b\x32\x12.bootz.Credentials\x12+\n\x05pathz\x18\x03 \x01(\x0b\x32\x1c.gnsi.pathz.v1.UploadRequest\x12+\n\x05\x61uthz\x18\x04 \x01(\x0b\x32\x1c.gnsi.authz.v1.UploadRequest\x12\x36\n\x0c\x63\x65rtificates\x18\x05 \x01(\x0b\x32\x1c.gnsi.certz.v1.UploadRequestB\x02\x18\x01\x12#\n\x05\x63\x65rtz\x18\x06 \x01(\x0b\x32\x14.bootz.CertzProfiles\"\x17\n\x15SetBootConfigResponse2\xd0\x01\n\nBootConfig\x12`\n\rGetBootConfig\x12%.gnoi.bootconfig.GetBootConfigRequest\x1a&.gnoi.bootconfig.GetBootConfigResponse\"\x00\x12`\n\rSetBootConfig\x12%.gnoi.bootconfig.SetBootConfigRequest\x1a&.gnoi.bootconfig.SetBootConfigResponse\"\x00\x42/Z%github.com/openconfig/gnoi/bootconfig\xd2>\x05\x30.1.0b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'github.com.openconfig.gnoi.bootconfig.bootconfig_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z%github.com/openconfig/gnoi/bootconfig\322>\0050.1.0'
  _globals['_SETBOOTCONFIGREQUEST'].fields_by_name['certificates']._loaded_options = None
  _globals['_SETBOOTCONFIGREQUEST'].fields_by_name['certificates']._serialized_options = b'\030\001'
  _globals['_GETBOOTCONFIGREQUEST']._serialized_start=306
  _globals['_GETBOOTCONFIGREQUEST']._serialized_end=328
  _globals['_GETBOOTCONFIGRESPONSE']._serialized_start=330
  _globals['_GETBOOTCONFIGRESPONSE']._serialized_end=393
  _globals['_SETBOOTCONFIGREQUEST']._serialized_start=396
  _globals['_SETBOOTCONFIGREQUEST']._serialized_end=682
  _globals['_SETBOOTCONFIGRESPONSE']._serialized_start=684
  _globals['_SETBOOTCONFIGRESPONSE']._serialized_end=707
  _globals['_BOOTCONFIG']._serialized_start=710
  _globals['_BOOTCONFIG']._serialized_end=918
# @@protoc_insertion_point(module_scope)
