# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from github.com.openconfig.gnoi.bootconfig import bootconfig_pb2 as github_dot_com_dot_openconfig_dot_gnoi_dot_bootconfig_dot_bootconfig__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in github.com/openconfig/gnoi/bootconfig/bootconfig_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BootConfigStub(object):
    """gNOI BootConfig service provides an API to update the boot configuration
    namespace as in the Bootz protocol (https://github.com/openconfig/bootz).
    This API is often used after the Bootz turnup workflow is finished.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBootConfig = channel.unary_unary(
                '/gnoi.bootconfig.BootConfig/GetBootConfig',
                request_serializer=github_dot_com_dot_openconfig_dot_gnoi_dot_bootconfig_dot_bootconfig__pb2.GetBootConfigRequest.SerializeToString,
                response_deserializer=github_dot_com_dot_openconfig_dot_gnoi_dot_bootconfig_dot_bootconfig__pb2.GetBootConfigResponse.FromString,
                _registered_method=True)
        self.SetBootConfig = channel.unary_unary(
                '/gnoi.bootconfig.BootConfig/SetBootConfig',
                request_serializer=github_dot_com_dot_openconfig_dot_gnoi_dot_bootconfig_dot_bootconfig__pb2.SetBootConfigRequest.SerializeToString,
                response_deserializer=github_dot_com_dot_openconfig_dot_gnoi_dot_bootconfig_dot_bootconfig__pb2.SetBootConfigResponse.FromString,
                _registered_method=True)


class BootConfigServicer(object):
    """gNOI BootConfig service provides an API to update the boot configuration
    namespace as in the Bootz protocol (https://github.com/openconfig/bootz).
    This API is often used after the Bootz turnup workflow is finished.
    """

    def GetBootConfig(self, request, context):
        """GetBootConfig gets the current boot config.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetBootConfig(self, request, context):
        """SetBootConfig replaces the existing boot config with the new provided one.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BootConfigServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBootConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBootConfig,
                    request_deserializer=github_dot_com_dot_openconfig_dot_gnoi_dot_bootconfig_dot_bootconfig__pb2.GetBootConfigRequest.FromString,
                    response_serializer=github_dot_com_dot_openconfig_dot_gnoi_dot_bootconfig_dot_bootconfig__pb2.GetBootConfigResponse.SerializeToString,
            ),
            'SetBootConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetBootConfig,
                    request_deserializer=github_dot_com_dot_openconfig_dot_gnoi_dot_bootconfig_dot_bootconfig__pb2.SetBootConfigRequest.FromString,
                    response_serializer=github_dot_com_dot_openconfig_dot_gnoi_dot_bootconfig_dot_bootconfig__pb2.SetBootConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gnoi.bootconfig.BootConfig', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gnoi.bootconfig.BootConfig', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BootConfig(object):
    """gNOI BootConfig service provides an API to update the boot configuration
    namespace as in the Bootz protocol (https://github.com/openconfig/bootz).
    This API is often used after the Bootz turnup workflow is finished.
    """

    @staticmethod
    def GetBootConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gnoi.bootconfig.BootConfig/GetBootConfig',
            github_dot_com_dot_openconfig_dot_gnoi_dot_bootconfig_dot_bootconfig__pb2.GetBootConfigRequest.SerializeToString,
            github_dot_com_dot_openconfig_dot_gnoi_dot_bootconfig_dot_bootconfig__pb2.GetBootConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetBootConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gnoi.bootconfig.BootConfig/SetBootConfig',
            github_dot_com_dot_openconfig_dot_gnoi_dot_bootconfig_dot_bootconfig__pb2.SetBootConfigRequest.SerializeToString,
            github_dot_com_dot_openconfig_dot_gnoi_dot_bootconfig_dot_bootconfig__pb2.SetBootConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
