# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: github.com/openconfig/gnsi/authz/authz.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'github.com/openconfig/gnsi/authz/authz.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,github.com/openconfig/gnsi/authz/authz.proto\x12\rgnsi.authz.v1\"\xce\x01\n\x12RotateAuthzRequest\x12\x36\n\x0eupload_request\x18\x01 \x01(\x0b\x32\x1c.gnsi.authz.v1.UploadRequestH\x00\x12;\n\x11\x66inalize_rotation\x18\x02 \x01(\x0b\x32\x1e.gnsi.authz.v1.FinalizeRequestH\x00\x12\x17\n\x0f\x66orce_overwrite\x18\x03 \x01(\x08\x12\x18\n\x10\x61uthz_profile_id\x18\x04 \x01(\tB\x10\n\x0erotate_request\"b\n\x13RotateAuthzResponse\x12\x38\n\x0fupload_response\x18\x01 \x01(\x0b\x32\x1d.gnsi.authz.v1.UploadResponseH\x00\x42\x11\n\x0frotate_response\"\x11\n\x0f\x46inalizeRequest\"D\n\rUploadRequest\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x12\n\ncreated_on\x18\x02 \x01(\x04\x12\x0e\n\x06policy\x18\x03 \x01(\t\"\x10\n\x0eUploadResponse\")\n\x0cProbeRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0b\n\x03rpc\x18\x02 \x01(\t\"\x9b\x01\n\rProbeResponse\x12\x33\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32#.gnsi.authz.v1.ProbeResponse.Action\x12\x0f\n\x07version\x18\x02 \x01(\t\"D\n\x06\x41\x63tion\x12\x16\n\x12\x41\x43TION_UNSPECIFIED\x10\x00\x12\x0f\n\x0b\x41\x43TION_DENY\x10\x01\x12\x11\n\rACTION_PERMIT\x10\x02\"\x0c\n\nGetRequest\"B\n\x0bGetResponse\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x12\n\ncreated_on\x18\x02 \x01(\x04\x12\x0e\n\x06policy\x18\x03 \x01(\t2\xde\x01\n\x05\x41uthz\x12S\n\x06Rotate\x12!.gnsi.authz.v1.RotateAuthzRequest\x1a\".gnsi.authz.v1.RotateAuthzResponse(\x01\x30\x01\x12\x42\n\x05Probe\x12\x1b.gnsi.authz.v1.ProbeRequest\x1a\x1c.gnsi.authz.v1.ProbeResponse\x12<\n\x03Get\x12\x19.gnsi.authz.v1.GetRequest\x1a\x1a.gnsi.authz.v1.GetResponseB\"Z github.com/openconfig/gnsi/authzb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'github.com.openconfig.gnsi.authz.authz_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z github.com/openconfig/gnsi/authz'
  _globals['_ROTATEAUTHZREQUEST']._serialized_start=64
  _globals['_ROTATEAUTHZREQUEST']._serialized_end=270
  _globals['_ROTATEAUTHZRESPONSE']._serialized_start=272
  _globals['_ROTATEAUTHZRESPONSE']._serialized_end=370
  _globals['_FINALIZEREQUEST']._serialized_start=372
  _globals['_FINALIZEREQUEST']._serialized_end=389
  _globals['_UPLOADREQUEST']._serialized_start=391
  _globals['_UPLOADREQUEST']._serialized_end=459
  _globals['_UPLOADRESPONSE']._serialized_start=461
  _globals['_UPLOADRESPONSE']._serialized_end=477
  _globals['_PROBEREQUEST']._serialized_start=479
  _globals['_PROBEREQUEST']._serialized_end=520
  _globals['_PROBERESPONSE']._serialized_start=523
  _globals['_PROBERESPONSE']._serialized_end=678
  _globals['_PROBERESPONSE_ACTION']._serialized_start=610
  _globals['_PROBERESPONSE_ACTION']._serialized_end=678
  _globals['_GETREQUEST']._serialized_start=680
  _globals['_GETREQUEST']._serialized_end=692
  _globals['_GETRESPONSE']._serialized_start=694
  _globals['_GETRESPONSE']._serialized_end=760
  _globals['_AUTHZ']._serialized_start=763
  _globals['_AUTHZ']._serialized_end=985
# @@protoc_insertion_point(module_scope)
